name: Basics
on:
  workflow_dispatch:
  
env:
  name: Juan
  number: 123

jobs:
  first-job:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, ${{ env.name }}!
        
      - run: gh issue create --title "Workflow issue" --body "Thank you for opening this issue!" 
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  second-job:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo Im running in parallel job
  
  third-job:
    runs-on: ubuntu-latest
    needs: first-job
    
    steps:
      - run: echo Im running in sequential job
