name: Basics
on:
  workflow_dispatch:

jobs:
  first-job:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!
        
  second-job:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo Im running in parallel job
  
  third-job:
    runs-on: ubuntu-latest
    needs: first-job
    
    steps:
      - run: echo Im running in sequential job
